# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QDesktopWidget, QApplication


class Ui_MainWindow(object):
    def __init__(self):
        super().__init__()
        self.title = None
        self.startButton = None

    def center(self):
        qr = self.frameGeometry()
        cp = QDesktopWidget().availableGeometry().center()
        qr.moveCenter(cp)
        self.move(qr.topLeft())


    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1500, 1500)

        self.mainMenu = QtWidgets.QWidget(MainWindow)
        self.mainMenu.setMaximumSize(QtCore.QSize(1500, 1500))
        self.mainMenu.setStyleSheet("background-color: rgb(255, 240, 253);\n"
                                    "color: rgb(255, 240, 253);")
        self.mainMenu.setObjectName("mainMenu")
        self.center()

        self.title = QtWidgets.QLabel(self.mainMenu)
        self.title.setGeometry(QtCore.QRect(200, 300, 600, 300))
        font = QtGui.QFont()
        font.setFamily("Algerian")
        font.setPointSize(48)
        self.title.setFont(font)
        self.title.setStyleSheet("background-color: rgb(255, 170, 255);\n"
                                 "border-radius: 15px; border-width: 3px;\n"
                                 "border-style: solid;\n"
                                 "border-color: rgb(195, 16, 117);")
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        self.startButton = QtWidgets.QPushButton(self.mainMenu)
        self.startButton.setGeometry(QtCore.QRect(420, 430, 161, 61))
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        font.setPointSize(20)
        self.startButton.setFont(font)
        self.startButton.setAutoFillBackground(False)
        self.startButton.setStyleSheet("background-color: rgb(218, 171, 255);\n"
                                       "border-radius: 15px; border-width: 3px;\n"
                                       "border-style: solid;\n"
                                       "border-color: rgb(135, 0, 203);")
        self.startButton.setObjectName("startButton")
        self.instructionButton = QtWidgets.QPushButton(self.mainMenu)
        self.instructionButton.setGeometry(QtCore.QRect(370, 540, 271, 61))
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        font.setPointSize(20)
        self.instructionButton.setFont(font)
        self.instructionButton.setAutoFillBackground(False)
        self.instructionButton.setStyleSheet("background-color: rgb(218, 171, 255);\n"
                                             "border-radius: 15px; border-width: 3px;\n"
                                             "border-style: solid;\n"
                                             "border-color: rgb(135, 0, 203);")
        self.instructionButton.setObjectName("instructionButton")
        MainWindow.setCentralWidget(self.mainMenu)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 989, 25))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionCopy = QtWidgets.QAction(MainWindow)
        self.actionCopy.setObjectName("actionCopy")
        self.actionPaste = QtWidgets.QAction(MainWindow)
        self.actionPaste.setObjectName("actionPaste")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionSave)
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionPaste)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title.setText(_translate("MainWindow", "Motion Mapper"))
        self.startButton.setText(_translate("MainWindow", "START"))
        self.instructionButton.setText(_translate("MainWindow", "INSTRUCTIONS"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionNew.setStatusTip(_translate("MainWindow", "Creates a new file. "))
        self.actionNew.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave.setStatusTip(_translate("MainWindow", "Saves the current file"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionCopy.setText(_translate("MainWindow", "Copy"))
        self.actionCopy.setStatusTip(_translate("MainWindow", "Copies the file"))
        self.actionCopy.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.actionPaste.setText(_translate("MainWindow", "Paste"))
        self.actionPaste.setStatusTip(_translate("MainWindow", "Pastes contents of the clipboard onto the file. "))
        self.actionPaste.setShortcut(_translate("MainWindow", "Ctrl+V"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
